### ISSUE TITLE
[Feature] Why don't you make it a button in the status bar called Start

### ISSUE THREAD

**Issue by AllanOricil** [ruige24601/vscode-plugin-vite#1]
Like this

![image](https://user-images.githubusercontent.com/55927613/87582978-29359d00-c6d3-11ea-8873-e5bd9ad93bf8.png)

I created this button to launch an automation I did with node. You can enable this button in projects that use Vue Js and then in the command you search for the Entry point (index.html) and launch the server.

**Comment by ruige24601** [comment]
Thanks to your reply. You can click it in status bar on right side, but can only start index.html in root path in current version. I will implement it in next version. 

![image](https://user-images.githubusercontent.com/57212574/87633238-9a299300-c76d-11ea-84c5-0499907ce8d7.png)

**Comment by AllanOricil** [comment]
> Thanks to your reply. You can click it in status bar on right side, but can only start index.html in root path in current version. I will implement it in next version.
> 
> ![image](https://user-images.githubusercontent.com/57212574/87633238-9a299300-c76d-11ea-84c5-0499907ce8d7.png)

Would be cool if they allowed to put custom icons in the Status bar. You could put Vue's icon
